source("R/ebs_rule_screening.R")
source("R/ebs_loader.R")
cat("ari vs varicella tag:", has_disease_tag("varicella", "ari"), "\n")
cat("ari vs malaria tag:", has_disease_tag("malaria", "ari"), "\n")
cat("ari vs ari tag:", has_disease_tag("ari,other", "ari"), "\n")
cat("typhoid vs paratyphoid tag:", has_disease_tag("paratyphoid", "typhoid"), "\n")
cat("typhoid vs typhoid tag:", has_disease_tag("typhoid", "typhoid"), "\n")
cat("gi vs legionella tag:", has_disease_tag("legionella", "gi"), "\n")
cat("gi vs giardia tag:", has_disease_tag("giardia", "gi"), "\n")
